### ISSUE TITLE
Berlin Hackathon 2019 - design session summary

### ISSUE THREAD

**Issue by ioleo** [zio/zio-web#15]
During the Berlin Hackathon 2019 there was a design session held for ZIO HTTP.
20 attendees discussed the scope and goals for the library (thanks to everyone for participating!).

### 1. Free client

We want to be able to generate clients from our API description for free.

### 2. Free documentation

We want to be able to generate documentation from our API description for free.

### 3. Free server

We want to be able to combine our API description with a matching handler to create a server.

### 4. Type safe route, request structure, response structure definitions

We want to make it impossible to express invalid APIs (such as a request being both a GET and POST at the same time) and we want it to be enforced by the compiler.

### 5. Streaming

Out of the box streaming support backed by ZIO Streams.

### 6. Web sockets

Web sockets should support should be part of the library.

### 7. Auth

We want to support common authentication and authorization schemes.

### 1. Generic vs HTTP only

There were propositions to make the library more generic and support binary protocols. After discussion we've decided to start with HTTP only and perhaps in future generalize the types adding more type parameters where necessary (and then HTTP-speficic types would become type aliases).

### 2. Service

Service is a description of what a server requires and provides. It should be a sum type with a number of terminal cases. By folding over the structure we may generate the client, documentation or a server (given handler for the service).

The description of the service `A => B` must be invertible such that we can generate a client `B => A`.

It will probably take a shape similar to `Service[In, SIn, Out, SOut, ErrIn, ErrOut]` where following pairs represent the input/output:

- `In` and `Out` payload (headers of HTTP message)
- `SIn` and `SOut` stream of data (body of HTTP message)
- `ErrIn` and `ErrOut` errors

With the base case being something like `Service[List[Header], Array[Byte], List[Header], Array[Bytes], ErrIn, ErrOut]`.

### 3. Handler

The handler represents the transformation from service input to its output. It will probably take a shape similar to `Handler[R, In, SIn, Out, SOut]`. Some points considered were:

- do we want to stick access to the current request in Handler's environment?
- it will require lots of combinators
- metrics out of the box
- integrate well with ZIO features such as timeout or interruption

### 4. Server

Server is just a ZIO effect that you get by combining a service with correct handler (the types must align), eg. `(Service, Handler) => ZIO[R, PortTaken, Nothing]`. We want to be as lazy as possible, ideally parsing as little as possible. Performance is not the top priority, but we don't want to be slower than average. We'd like to optimize the filters such that we know beforehand exacly what we're looking for, so we don't have to parse the full header.

### 5. Schema

We need a way to model the structure of our inputs and outputs, which will allow us to generate nice documentation and support diffrent encodings (eg. JSON, XML). Possibly with a schema evolution mechanism `Schema[A] => Schema[A]`.

### 6. Metadata

This was briefly mentioned, but I don't have any notes on that.

**Comment by dgouyette** [comment]
Free executable documentation ( open API ?) would be even better

**Comment by ioleo** [comment]
@dgouyette If we have the capability to inspect the API structure, then we can generate documentation from it in any format (eg. OpenAPI, Swagger, RAML). From the API doc we could leverage existing tools to generate clients.

**Comment by dgouyette** [comment]
I made something like that for play framework and refined, maybe i can help ;)

**Comment by shankarshastri** [comment]
Anything on GRPC or HTTP2?

**Comment by st33v3** [comment]
It is unclear that you are aiming to just remodel HTTP communication to form of above Service trait and wrap some already existing HTTP communication library or if your goal is to build self contained HTTP server/client on top of mere java nio socket.
In later case how do you plan to parse input byte stream? Something in spirit of play iteratees?

**Comment by ioleo** [comment]
@shankarshastri The plan is to start with HTTP, then extend to other protocols.
@st33v3 We want our own HTTP server, implemented on top `zio-nio` which is a ZIO wrapper on java nio API.

**Comment by vitaly-pushkar** [comment]
I believe it would be more intuitive to rename `Service` to `ServiceDefinition`.

`Service` as a name is too ambiguous and in this context even confusing.

Instead, `ServiceDefinition` makes it clear that you as a user of the library are merely _describing_ a service - not actually creating it.

**Comment by vitaly-pushkar** [comment]
Also, I am confused about the meaning of the "5. Streaming" Requirement.

Initially, I assumed that it's about HTTP/2 Streaming. 

But HTTP/2 Streaming requires working with binary payloads which as I understand is something this library is not going to tackle at the moment. 

What am I missing?

**Comment by ioleo** [comment]
HTTP is just a start. We do plan to support other protocols (including binary ones) in future. From the top of my head: HTTP2, HTTP3, QUIC, HLS, DASH, and probably many others. On the server side, we'd like to work with ZStream and Chunk API. How do we exacly achieve that given that these protocols may vary a lot in details? This is still an open question. Will `zio-http` be a generic library that incoroporates all of that or will be spawn a new one, makeing `zio-http` just an implementation for HTTP? That also remains to be seen. What is clear now is:
- we need a ZIO-based HTTP library as soon as possible to make it easier to switch to ZIO
- we need a reference implementation to validate our model before we start abstracting over the protocol and HTTP is most widely known, so it should make it easier for everyone to contribute

**Comment by st33v3** [comment]
HTTP server, implemented on top zio-nio - nice and ambitious. Reason I was asking is that I some time ago started to write byte stream parser library for Akka Streams. I believe it could be ported to process byte Chunks. The library goal was to provide composable parsers (as in Scala parser combinators) but processing potentially infinite stream - variation of Iteratee approach.
I could contribute it if you are interested.

**Comment by mschuwalow** [comment]
@st33v3 I think you should definitely contribute it. There is talk about making a zio-codec library which I believe would be a very good home for this.
@mijicd what do you think?

**Comment by mijicd** [comment]
@mschuwalow @st33v3 I'd love to see this. As Maxim mentioned, we're in the process of pitching / scratching `zio-codec` library. This looks like a very nice addition to it.

**Comment by st33v3** [comment]
@mschuwalow @mijicd Ok. We should probably bring this discussion out of this issue. Does zio-codec have its own Github project? In meantime I will publish my parser library so you can take a look.
Regarding of zio-codec - do you have design document of some kind? I think that lot of issues should be considered. For example what is your opinion on how codecs should interoperate with rest of ZIO ecosystem? Should they operate on ZStreams or should they be standalone? What is proper container for byte sequences? Java ByteBuffer is not immutable, Chunk[Byte] would lead to boxing of bytes (I'm afraid).

**Comment by mijicd** [comment]
@st33v3 Still no repository, the library is in (very) early design phase. Based on what I discussed with @mschuwalow, we'll aim for providing the same set of capabilities as scodec and boopickle. Please reach out to either of us over discord, and let's schedule a design session together.
