### ISSUE TITLE
Encode OpenAPI Specification

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-web#19]
The services of zio-http should have a type safe descriptions
that are seperate from implementation and can be used to generate documentation
in common standards.
OpenAPI is the gold standard for REST APIs and should be fully supported.

As a first step a scala representation of the OpenApi Specification should be implemented.

/cc @mijicd

**Comment by mijicd** [comment]
cc @kellydavid

**Comment by er1c** [comment]
Would this cover client generation based upon a swagger/openapi?
