### ISSUE TITLE
Encode AsyncAPI Specification

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-web#20]
The services of zio-http should have a type safe descriptions
that are seperate from implementation and can be used to generate documentation
in common standards.
Alongside REST we want to support websockets and http streaming which are both not supported by OpenAPI.

It seems like AsyncAPI is becoming a dominant standard for this and should be the main documentation
standard we support for streaming endpoints.

As a first step a scala representation of the AsyncAPI Specification should be implemented.

/cc @mijicd

**Comment by co-category** [comment]
@mschuwalow I can start looking into this. Not attempted anything like this but I guess we want a Scala parser that can read any service defined in terms of the AsyncAPI specification and then be able to use that representation to subsequently produce anything e.g. zio-http code, documentation etc.

**Comment by mschuwalow** [comment]
Hmm I believe that we might want to go the other way. So given a service or some kind of service definition create a datastructure that can be materialized into AsyncApi json or yaml. 
The interesting thing to consider here is how we want to deal with that fact that our services are too powerful for the AsyncApi spec, so we may only want to expose the streaming routes or similar

**Comment by co-category** [comment]
I see what you mean now. That's very interesting; will have a think about and do a bit of research.

**Comment by co-category** [comment]
One approach could be to create a `Doc` typeclass and any `zio-http` type which is used to construct an API would provide an instance of this typeclass. A very basic implementation of the idea is the following:

```scala
trait Doc[A] {
  def doc(a: A): String   // return string for now, exact type TBC
}

object Doc {

  def apply[A](implicit doc: Doc[A]): Doc[A] = doc

  object ops {
    def doc[A: Doc](a: A) = Doc[A].doc(a)

    implicit class DocOps[A: Doc](a: A) {
      def doc = Doc[A].doc(a)
    }
  }

  implicit val docRequestHeader: Doc[RequestHeader] =
    header => s"int $header"

  implicit val docAcceptRanges: Doc[AcceptRanges] =
    ar => s"string $ar"

}
```
This would allow an intermediate abstract structured description of the API documentation which can then be converted to various formats: markdown, yaml, json e.g.

```scala
   def asyncApi[A](apiDoc : Doc[A]) : AsyncApiDoc
```
where `A` represents the `zio-http` type representing the complete description of the service.

@mschuwalow @ioleo WDYT?

**Comment by mschuwalow** [comment]
Yes, something like this looks like a good choice. 👍
I think the scope for this issue is mostly just modeling the the AsyncApi side so `AsyncApiDoc` in your example. I think it's best to move discussion about how exactly they should interact to https://github.com/zio/zio-http/issues/21

**Comment by co-category** [comment]
Cool, I've started work on that so should have something in a few days...

**Comment by co-category** [comment]
> Hmm I believe that we might want to go the other way. So given a service or some kind of service definition create a datastructure that can be materialized into AsyncApi json or yaml.
> The interesting thing to consider here is how we want to deal with that fact that our services are too powerful for the AsyncApi spec, so we may only want to expose the streaming routes or similar

The good thing about the AsyncApi specification is that it allows custom extensions. So if zio-http has capabilities which are not readily translatable into the current version of the specification we could add our own custom specification to cater for it.
