### ISSUE TITLE
HTTP model for Request

### ISSUE THREAD

**Issue by ioleo** [zio/zio-web#4]
Create `zio.http.Request` that will model the HTTP request.

**Comment by st33v3** [comment]
Are you familiar with HTTP model of Akka Streams project? I think they made great deal of work modeling all aspects of HTTP communication including SSL/TLS configuration. Wouldn't be possible to reuse it?

**Comment by co-category** [comment]
I'll take this one, but the type will go under the `zio.http.model` package as discussed [here](https://github.com/zio/zio-http/pull/18#issuecomment-553329380))
