### ISSUE TITLE
Implement proper logging HttpMiddleware

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-web#71]
There is an `HttpMiddleware.logging` middleware, but it is not completed. It should be rewritten to utilize the [Common Log Format](https://en.wikipedia.org/wiki/Common_Log_Format), as well as be more flexible where it places the log output, possibly using a `ZSink` from ZIO Streams to accept all the log lines.

This ticket will be done when the logging middleware can write to file output and writes in the common log format, with tests for both.

**Comment by anovakovic01** [comment]
I would like to try this one.
