### ISSUE TITLE
Add GrpcCodec.scala in zio.web.codec

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-web#75]
Add a gRPC Codec in `zio.web.codec`, which provides encoding/decoding transducers, which are capable of translating values to and from GRPC-encoded data. 

Probably, the `GrpcCodec` object should have some utility methods to print out the protobuf files for any schema. Then test suites can verify that whatever protobuf files are generated, the format of the data encoded/decoded actually corresponds to the structure of the protobuf files.

This ticket is ideal for someone who already has familiarity with gRPC / protobuf.

**Comment by eriktim** [comment]
I've worked on protobuf encoding/decoding transducers before so I would like to give this one a try.

**Comment by eriktim** [comment]
@jdegoes

Here are some initial questions/remarks:
* `.proto` files normally provide field numbers (used to identify chunks in the stream). If I understand it correctly a dev will just define a `Schema` type here which of course does not provide these numbers. I suggest using the index of fields in `Map`s as the field numbers.
* I think the codec should be called `ProtobufCodec` as the codec itself has nothing to do with gRPC.
* I assume we are aiming for Protobuf 3 here, or are there also plans to support Protobuf 2?
* What exactly do you suggest using the outputted Protobuf files (`.proto`) for? I think this codec can be best tested by encoding and decoding schemas and comparing the output to the input (using property based testing). Moreover, these `.proto` files may also contain the available gRPC requests which go beyond the codec.

**Comment by jdegoes** [comment]
@eriktim 

1. We need to modify `Schema` to use an `SortedMap`, so we can preserve the order of keys. Then we can use the key ordering in the map for the field numbers. Also the Magnolia derivation of `Schema` can take pains to ensure the order of fields in case classes is correctly preserved in the sorted map.
2. Yes, that's right, `ProtobufCodec` is a good name.
3. I think starting with Protobuf 3 is not a bad idea. A user could always add `Protobuf2` later.
4. I suggest that a user will want to output proto files containing services, for purposes of interop with other languages and all the machinery that exists in them. Example: I define my endpoints using _ZIO Web_, and then I generate the protofiles, and then I use those to generate a Java client library that uses gRPC to interact with my gRPC-deployed endpoints defined in ZIO Web.

Now the protobuf files for the `Endpoints` will be more than just the `message` for the request/response types. They will include `service` definitions as well. That's beyond the scope of this ticket.
